#spring:
#  datasource:
#    url: jdbc:h2:mem:dbtest
#    username: sa
#    password: pass
#  jpa:
#    show-sql: true
#    database-platform: org.hibernate.dialect.H2Dialect
#    defer-datasource-initialization: true
#    hibernate:
#      ddl-auto: create


spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus 